create table if not exists public.waitlist_signups (
  id bigint generated by default as identity primary key,
  email text not null unique,
  ip_address text,
  source text,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists waitlist_signups_created_at_idx
on public.waitlist_signups (created_at desc);
